### ISSUE TITLE
shouldn't we warm up EBS before we warm up OpenShift? 

### ISSUE THREAD

**Issue by edseymour** [RedHatEMEA/aws-ose3#10]
At the moment the ebs warmup is asynchronous, but perhaps it should be done before we 'warm up' openshift by downloading images, and running builds.

**Comment by jim-minter** [comment]
Not convinced - everything *should* work without the warmup, and making it synchronous at the top just lengthens the testing cycle.

**Comment by jim-minter** [comment]
Ed - I came round to your correct point of view eventually - this is done in 3.1.1 :-)

**Comment by edseymour** [comment]
Ahh, the system works :+1:
