### ISSUE TITLE
Possible issue with transition from instance IDs to reserve IDs

### ISSUE THREAD

**Issue by edseymour** [RedHatEMEA/aws-ose3#11]
Need to verify that scripts continue to work. 
InstanceID field is no longer populated, so likely to cause issues

**Comment by jim-minter** [comment]
@edseymour, more information please.
I'm aware AWS are lengthening the instanceid field - this shouldn't cause us an issue as it is used little and opaquely.
I don't understand what you mean by 'instanceid field is no longer populated' or 'reserve IDs' ?

**Comment by edseymour** [comment]
I was probably having a senior moment... 
InstanceIDs are very much still populated.
