### ISSUE TITLE
warm ebs using fio instead of dd

### ISSUE THREAD

**Issue by edseymour** [RedHatEMEA/aws-ose3#9]
According to Amazon docs using fio is considerably faster than dd as it supports consecutive reads. Although, it may need to be installed.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-initialize.html

**Comment by jim-minter** [comment]
Probably the best bet for getting fio is http://pkgs.repoforge.org/fio/fio-2.1.10-1.el7.rf.x86_64.rpm ; it requires libaio which will need to be included in the base image.

**Comment by jim-minter** [comment]
After much messing around, I'm convinced that fio simply isn't faster - the Amazon docs lie!

**Comment by edseymour** [comment]
Thanks for trying though!

On 23 February 2016 at 17:20, Jim Minter <notifications@github.com> wrote:

> After much messing around, I'm convinced that fio simply isn't faster -
> the Amazon docs lie!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedHatEMEA/aws-ose3/issues/9#issuecomment-187798406>.
>



-- 


Ed Seymour
OpenShift Specialist Solution Architect
Tel: +44 (0)1252 362957
Mob: +44 (0)7876 883770

Red Hat
